Repository owncloud/docs-server, pull requests merged in 2022-10, with the labels that each got.

#662 Revert "[10.11] [PR 658] doc update for owncloud/core#40389"
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#663 Revert "[10.10] [PR 658] doc update for owncloud/core#40389"
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#666 Added Backblaze S3 primary example
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: documentation, enhancement, backport, admin docs

#674 [10.10] [PR 669] fix apache header merge command
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: backport

#673 [10.11] [PR 669] fix apache header merge command
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: backport

#672 [10.10] [PR 670] add hint for db backups while using s3
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#671 [10.11] [PR 670] add hint for db backups while using s3
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#668 [master] [PR 666] Added Backblaze S3 primary example
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#677 Add youtube video for document classification
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: documentation

#678 [10.11] [PR 677] Add youtube video for document classification
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: backport

#679 [10.10] [PR 677] Add youtube video for document classification
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: backport

#680 [10.11] [PR 676] add MyQnapCloud configuration and reverse proxy
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#681 [10.10] [PR 676] add MyQnapCloud configuration and reverse proxy
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#683 Update the user management documentation
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: documentation

#684 [10.11] [PR 683] Update the user management documentation
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#685 [10.10] [PR 683] Update the user management documentation
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#688 [10.11] [PR 686] Review of user_management page
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#689 [10.10] [PR 686] Review of user_management page
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#690 [10.11] [PR 687] Fixup quota explanation
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#691 [10.10] [PR 687] Fixup quota explanation
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#695 [10.10] [PR 693] add documentation for trusted domain container env
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#694 [10.11] [PR 693] add documentation for trusted domain container env
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport
