Repository owncloud/docs-server, pull requests merged in 2022-11, with the labels that each got.

#704 Update S3 Primary documentation
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: admin docs

#705 Config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#706 [10.11] [PR 705] Config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#707 [10.10] [PR 705] Config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#708 [10.11][704] Update S3 Primary documentation
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#709 [10.10][704] Update S3 Primary documentation
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#712 [10.11] [PR 711] Clarify 2FA usage with desktop and mobile apps
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Labels: backport

#713 [10.10] [PR 711] Clarify 2FA usage with desktop and mobile apps
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Labels: backport

#715 [10.11] [PR 710] Update upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
Labels: backport

#716 [10.10] [PR 710] Update upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
Labels: backport

#714 Update 2FA and OAuth2
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Labels: admin docs

#717 [10.11] [PR 714] Update 2FA and OAuth2
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Labels: backport

#718 [10.10] [PR 714] Update 2FA and OAuth2
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Labels: backport

#723 Fix VirtualHost parameter
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: admin docs

#724 [10.10] [PR 723] Fix VirtualHost parameter
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: backport

#725 [10.11] [PR 723] Fix VirtualHost parameter
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: backport

#727 [10.11] [PR 722] Example USER DN
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#728 Improve ICAP text
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: admin docs

#729 [10.11] [PR 728] Improve ICAP text
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#730 [10.10] [PR 728] Improve ICAP text
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#731 Config-to-docs run for openidconnect
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#733 [10.11] [PR 731] Config-to-docs run for openidconnect
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#734 [10.10] [PR 731] Config-to-docs run for openidconnect
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#743 Update files:scan not to be used with S3
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Labels: admin docs

#744 [10.11] [PR 743] Update files:scan not to be used with S3
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Labels: backport

#745 [10.10] [PR 743] Update files:scan not to be used with S3
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Labels: backport

#746 Update Antivirus forced by App update for ICAP
  modules/admin_manual/images/apps/files_antivirus/antivirus-daemon-socket.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-daemon.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-executable.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-icap.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-configuration-rules.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-host-connection-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-misconfiguration-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-socket-connection-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-panel.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/antivirus-app.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/antivirus-logging.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/av_modes.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_daemon_socket.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_daemon_tcp.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_executable.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_clamav.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_fortinet.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_mcafee.png
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: admin docs

#747 [10.11] [PR 746] Update Antivirus forced by App update for ICAP
  modules/admin_manual/images/apps/files_antivirus/antivirus-daemon-socket.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-daemon.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-executable.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-icap.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-configuration-rules.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-host-connection-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-misconfiguration-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-socket-connection-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-panel.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/antivirus-app.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/antivirus-logging.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/av_modes.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_daemon_socket.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_daemon_tcp.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_executable.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_clamav.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_fortinet.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_mcafee.png
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#748 [10.10] [PR 746] Update Antivirus forced by App update for ICAP
  modules/admin_manual/images/apps/files_antivirus/antivirus-daemon-socket.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-daemon.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-executable.png
  modules/admin_manual/images/apps/files_antivirus/antivirus-icap.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-configuration-rules.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-host-connection-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-misconfiguration-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-message-socket-connection-problem.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/anti-virus-panel.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/antivirus-app.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/antivirus-logging.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/av_modes.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_daemon_socket.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_daemon_tcp.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/clamav_executable.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_clamav.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_fortinet.png
  modules/admin_manual/images/configuration/server/virus-scanner-support/icap_mcafee.png
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#750 [10.10] [PR 749] Files are also scanned on download
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#752 Rename Classic Server (no reference changes)
  antora.yml
Labels: admin docs, developer docs

#754 [10.11] [PR 752] Rename Classic Server (no reference changes)
  antora.yml
Labels: backport

#756 Fix antora.yml (the backport overwrote accidentially the version)
  antora.yml
Labels: backport
