Repository owncloud/docs-server, pull requests merged in 2022-08, with the labels that each got.

#564 [10.10] [PR 563] Update generated volume name in index.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#565 [10.9] [PR 563] Update generated volume name in index.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#567 [10.10] [PR 566] Missing required configuration
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: admin docs

#568 [10.9] [PR 566] Missing required configuration
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: admin docs

#569 language review
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: admin docs

#570 [10.10] [PR 569] language review
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: backport

#571 [10.9] [PR 569] language review
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: backport

#576 [10.10] [PR 575] Clarify setting of integrity.ignore.missing.app.signature
  modules/developer_manual/pages/core/theming.adoc
Labels: backport

#577 [10.9] [PR 575] Clarify setting of integrity.ignore.missing.app.signature
  modules/developer_manual/pages/core/theming.adoc
Labels: backport

#580 Remove write-good from dependency.yml
  .github/dependabot.yml
Labels: dependencies

#581 Fix configreport and logging
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
  modules/admin_manual/partials/nav.adoc
  site.yml
Labels: admin docs

#583 [10.9] [PR 581] Fix configreport and logging
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
  modules/admin_manual/partials/nav.adoc
  site.yml
Labels: backport

#582 [10.10] [PR 581] Fix configreport and logging
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
  modules/admin_manual/partials/nav.adoc
  site.yml
Labels: backport

#524 config apps sample update (openidconnect)
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#562 config.apps.sample changes via core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#587 [10.10] [PR 524] config apps sample update (openidconnect)
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#588 [10.9] [PR 524] config apps sample update (openidconnect)
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#589 Config-to-docs run from latest core changes
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: documentation

#590 [10.10] [PR 589] Config-to-docs run from latest core changes
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#591 [10.9] [PR 589] Config-to-docs run from latest core changes
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport
