Repository owncloud/docs-server, pull requests merged in 2022-05, with the labels that each got.

#296 Switch to Primary and Replica terminology
  modules/admin_manual/images/installation/deprecs-2.png
  modules/admin_manual/images/installation/deprecs-3.png
Labels: documentation, enhancement

#297 [10.9] [PR 296] Switch to Primary and Replica terminology
  modules/admin_manual/images/installation/deprecs-2.png
  modules/admin_manual/images/installation/deprecs-3.png
Labels: backport

#298 [10.8] [PR 296] Switch to Primary and Replica terminology
  modules/admin_manual/images/installation/deprecs-2.png
  modules/admin_manual/images/installation/deprecs-3.png
Labels: backport

#301 Config To Docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#302 [10.9] [PR 301] Config To Docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#303 [10.8] [PR 301] Config To Docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#305 [10.8] [PR 300] Update manual_upgrade.adoc (addendum to #285)
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#309 [10.9] [PR 307] Update the section for manual file locking in admin settings
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
Labels: backport

#310 branching text fix
  docs/new-version-branch.md
Labels: deployment

#315 [10.8] [PR 313] Invert description of auto-app-update logic
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#314 [10.9] [PR 313] Invert description of auto-app-update logic
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#316 Changes necessary for 10.10
  .drone.star
  site.yml
Labels: deployment

#317 [10.10] [PR 312] mention enable files_external app
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: backport

#323 [10.10] [PR 322] Just a small backlink to the previews configuration
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#324 [10.9] [PR 322] Just a small backlink to the previews configuration
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#325 [10.8] [PR 322] Just a small backlink to the previews configuration
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#327 Adding global attribute for ocis
  site.yml
Labels: deployment

#328 [10.10] [PR 327] Adding global attribute for ocis
  site.yml
Labels: backport

#329 [10.9] [PR 327] Adding global attribute for ocis
  site.yml
Labels: backport

#330 [10.8] [PR 327] Adding global attribute for ocis
  site.yml
Labels: backport

#331 [10.10] [PR 326] add note about custom theme
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: backport

#332 [10.9] [PR 326] add note about custom theme
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: backport

#333 [10.8] [PR 326] add note about custom theme
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: backport

#334 New syntax for config stored passwords
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
Labels: admin docs

#335 [10.10] [PR 334] New syntax for config stored passwords
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
Labels: backport

#336 [10.9] [PR 334] New syntax for config stored passwords
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
Labels: backport

#337 [10.10] [PR 255] O365 integration
  .gitignore
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#339 [10.8] [PR 255] O365 integration
  .gitignore
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#338 [10.9] [PR 255] O365 integration
  .gitignore
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#340 [10.10] [PR 233] updated php-soap instructions for sharepoint.
  modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
Labels: backport

#341 [10.9] [PR 233] updated php-soap instructions for sharepoint.
  modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
Labels: backport

#342 [10.8] [PR 233] updated php-soap instructions for sharepoint.
  modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
Labels: backport

#343 Language review sample php
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#345 [10.9] [PR 343] Language review sample php
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#346 [10.10] [PR 343] Language review sample php
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#348 Fixing ticks in msoffice-wopi
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: admin docs

#352 [10.8] [PR 348] Fixing ticks in msoffice-wopi
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#350 [10.9] [PR 348] Fixing ticks in msoffice-wopi
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#351 [10.10] [PR 348] Fixing ticks in msoffice-wopi
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#353 config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#356 [10.8] [PR 353] config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#355 [10.9] [PR 353] config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#359 [10.10] [PR 358] Fix command line display on SAML page
  modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
Labels: backport

#362 [10.10] [PR 357] shareType can't be optional if shareType is 1 or 0
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#364 [10.8] [PR 357] shareType can't be optional if shareType is 1 or 0
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#363 [10.9] [PR 357] shareType can't be optional if shareType is 1 or 0
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#373 Temporary fix for the openSSL v3 incompatibility
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: admin docs

#375 [10.9] [PR 373] Temporary fix for the openSSL v3 incompatibility
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#376 [10.8] [PR 373] Temporary fix for the openSSL v3 incompatibility
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#377 Micosoft Azure and Redirect URI info
  modules/admin_manual/images/configuration/user/oidc/ms-azure-ad/ms-azure-manifest.png
  modules/admin_manual/images/configuration/user/oidc/ms-azure-ad/provide-required-information-ms-azure-ad.png
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: admin docs

#378 [10.10] [PR 377] Micosoft Azure and Redirect URI info
  modules/admin_manual/images/configuration/user/oidc/ms-azure-ad/ms-azure-manifest.png
  modules/admin_manual/images/configuration/user/oidc/ms-azure-ad/provide-required-information-ms-azure-ad.png
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#379 [10.9] [PR 377] Micosoft Azure and Redirect URI info
  modules/admin_manual/images/configuration/user/oidc/ms-azure-ad/ms-azure-manifest.png
  modules/admin_manual/images/configuration/user/oidc/ms-azure-ad/provide-required-information-ms-azure-ad.png
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#380 Fix typo
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: admin docs

#382 [10.9] [PR 380] Fix typo
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport
