Repository owncloud/docs-server, pull requests merged in 2022-04, with the labels that each got.

#234 Update general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
Labels: admin docs

#235 [10.9] [PR 234] Update general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
Labels: backport

#236 [10.8] [PR 234] Update general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
Labels: backport

#237 Update manual_imagick7.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: admin docs

#239 [10.8] [PR 237] Update manual_imagick7.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#243 [10.9] [PR 241] put the user-key is legacy in the title
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#244 [10.8] [PR 241] put the user-key is legacy in the title
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#245 fix wording
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: admin docs

#246 [10.9] [PR 242] remove user-key from quick guide
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
Labels: backport

#247 [10.8] [PR 242] remove user-key from quick guide
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
Labels: backport

#249 [10.8] [PR 245] fix wording
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#248 [10.9] [PR 245] fix wording
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#251 Fixes to user_auth_ldap
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: admin docs

#253 [10.9] [PR 251] Fixes to user_auth_ldap
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#254 [10.8] [PR 251] Fixes to user_auth_ldap
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#258 [master] [PR 257] Update oauth2.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: backport

#259 [10.8] [PR 257] Update oauth2.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: backport

#260 MySQL Backup Use Single Transaction
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
Labels: admin docs

#261 [10.9] [PR 260] MySQL Backup Use Single Transaction
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
Labels: backport

#262 [10.8] [PR 260] MySQL Backup Use Single Transaction
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
Labels: backport

#263 Add WOPI Business Key
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#264 [10.9] [PR 263] Add WOPI Business Key
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#265 [10.8] [PR 263] Add WOPI Business Key
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#268 Revert "[10.8] [PR 263] Add WOPI Business Key"
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#267 Revert "[10.9] [PR 263] Add WOPI Business Key"
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#266 Revert "Add WOPI Business Key"
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#269 Relocate files_classifier document
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
  modules/admin_manual/pages/enterprise/document_classification/index.adoc
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#270 [10.9] [PR 269] Relocate files_classifier document
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
  modules/admin_manual/pages/enterprise/document_classification/index.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#271 [10.8] [PR 269] Relocate files_classifier document
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
  modules/admin_manual/pages/enterprise/document_classification/index.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#276 [10.9] [PR 275] Remove warning in OAuth2 doc
  modules/admin_manual/pages/configuration/user/user_oauth2.adoc
Labels: backport

#281 [master] [PR 280] Update system_requirements.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#282 [10.8] [PR 280] Update system_requirements.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#286 Update manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: admin docs

#287 [10.9] [PR 286] Update manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#288 [10.8] [PR 286] Update manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#291 [10.9] [PR 290] replace deprecated download.owncloud.org url
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  site.yml
Labels: backport

#293 Update site.yml
  site.yml
Labels: deployment

#294 [10.9] [PR 293] Update site.yml
  site.yml
Labels: backport

#295 [10.8] [PR 293] Update site.yml
  site.yml
Labels: backport
