Repository owncloud/docs-server, pull requests merged in 2022-12, with the labels that each got.

#757 Add yarn-bundle command
  package.json
Labels: deployment

#760 [10.10] [PR 758] Config-to-docs run for changes in core
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#759 [10.11] [PR 758] Config-to-docs run for changes in core
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#762 Improve visibility that files:scan is not possible for S3
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Labels: admin docs

#764 [10.11] [PR 762] Improve visibility that files:scan is not possible for S3
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Labels: backport

#765 Fix a remnant of the term classic
  modules/ROOT/pages/index.adoc
Labels: admin docs

#767 [10.10] [PR 765] Fix a remnant of the term classic
  modules/ROOT/pages/index.adoc
Labels: backport

#768 More improvements for S3, files scan and BG jobs
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_background_jobs_selector.adoc
Labels: admin docs

#769 [10.10] [PR 768] More improvements for S3, files scan and BG jobs
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_background_jobs_selector.adoc
Labels: backport

#770 [10.11] [PR 768] More improvements for S3, files scan and BG jobs
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_background_jobs_selector.adoc
Labels: backport

#772 Update of the guest app description
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: admin docs

#774 [10.11] [PR 772] Update of the guest app description
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: backport

#773 [10.10] [PR 772] Update of the guest app description
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: backport

#775 Fix broken (internal) links
  modules/admin_manual/pages/configuration/general_topics/search.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
Labels: admin docs

#776 [10.11] [PR 775] Fix broken (internal) links
  modules/admin_manual/pages/configuration/general_topics/search.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
Labels: backport

#777 [10.10] [PR 775] Fix broken (internal) links
  modules/admin_manual/pages/configuration/general_topics/search.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#779 Add sudo on piped commands
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: documentation

#781 [10.11] [PR 779] Add sudo on piped commands
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#780 [10.10] [PR 779] Add sudo on piped commands
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#784 [10.10] [PR 782] Apache rewriteRule requires mod_rewrite and no leading / in .htaccess
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#783 [10.11] [PR 782] Apache rewriteRule requires mod_rewrite and no leading / in .htaccess
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport
