Repository owncloud/docs-server, pull requests merged in 2022-06, with the labels that each got.

#387 [10.10] [PR 386] More explicit description about platform config
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: backport

#388 [10.9] [PR 386] More explicit description about platform config
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: backport

#389 Caching configuration update
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: admin docs

#391 [10.9] [PR 389] Caching configuration update
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#398 [10.10] [PR 393] Added description about handling in docker
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: backport

#400 [10.8] [PR 393] Added description about handling in docker
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: backport

#401 Make the openSSL prerequisite more prominent
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: admin docs

#402 [10.10] [PR 401] Make the openSSL prerequisite more prominent
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#403 [10.9] [PR 401] Make the openSSL prerequisite more prominent
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#404 [10.8] [PR 401] Make the openSSL prerequisite more prominent
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#405 Added documentation for OneLogin OIDC
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-oidc-configuration.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-oidc-sso.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-select-application.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-select-openid-app.png
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
  modules/admin_manual/pages/configuration/user/oidc/onelogin-setup.adoc
Labels: admin docs

#406 [10.10] [PR 405] Added documentation for OneLogin OIDC
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-oidc-configuration.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-oidc-sso.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-select-application.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-select-openid-app.png
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
  modules/admin_manual/pages/configuration/user/oidc/onelogin-setup.adoc
Labels: backport

#407 [10.9] [PR 405] Added documentation for OneLogin OIDC
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-oidc-configuration.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-oidc-sso.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-select-application.png
  modules/admin_manual/images/configuration/user/oidc/onelogin/onelogin-select-openid-app.png
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
  modules/admin_manual/pages/configuration/user/oidc/onelogin-setup.adoc
Labels: backport

#408 Fixed upper and lower case
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: admin docs

#409 [master] [PR 408] Fixed upper and lower case
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: backport

#410 [10.9] [PR 408] Fixed upper and lower case
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: backport

#411 occ custom groups
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_custom_groups.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: admin docs

#414 [10.8] [PR 411] occ custom groups
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_custom_groups.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#416 [10.10] [PR 415] fix: fix more deprecated download urls
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#417 [10.9] [PR 415] fix: fix more deprecated download urls
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#418 update encryption
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: admin docs

#419 [10.10] [PR 418] update encryption
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#420 [10.9] [PR 418] update encryption
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#421 [10.8] [PR 418] update encryption
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#422 Added note about the user filter execution
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: admin docs

#423 [10.10] [PR 422] Added note about the user filter execution
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#424 [10.9] [PR 422] Added note about the user filter execution
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#426 [10.10] [PR 425] Fix Database Upgrade MariaDB 10.6
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_database_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_database_conversion_commands.adoc
  modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
Labels: backport

#427 [10.9] [PR 425] Fix Database Upgrade MariaDB 10.6
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_database_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_database_conversion_commands.adoc
  modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
Labels: backport

#429 [10.10] [PR 428] Update using_letsencrypt.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: backport

#430 [10.9] [PR 428] Update using_letsencrypt.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: backport

#431 Remove an ocis attribute no longer used
  site.yml
Labels: deployment

#433 [10.9] [PR 431] Remove an ocis attribute no longer used
  site.yml
Labels: backport

#434 [10.8] [PR 431] Remove an ocis attribute no longer used
  site.yml
Labels: backport

#438 [10.8] [PR 435] Current version is beta.3
  site.yml
Labels: backport

#437 [10.9] [PR 435] Current version is beta.3
  site.yml
Labels: backport

#436 [10.10] [PR 435] Current version is beta.3
  site.yml
Labels: backport

#439 Fixing broken anchors
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: admin docs

#440 [10.10] [PR 439] Fixing broken anchors
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: backport

#442 fix phpunit url to prevent a 404
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: developer docs

#443 [10.10] [PR 442] fix phpunit url to prevent a 404
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: backport

#444 [10.9] [PR 442] fix phpunit url to prevent a 404
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: backport

#445 fix vda url
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: admin docs

#446 [10.10] [PR 445] fix vda url
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: backport

#447 [10.9] [PR 445] fix vda url
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: backport

#451 Update files sharing configuration
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: admin docs

#453 [10.9] [PR 451] Update files sharing configuration
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: backport

#455 [10.9] [PR 450] Removed all occurrences of php prefixing
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#454 [10.10] [PR 450] Removed all occurrences of php prefixing
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#457 [10.10] [PR 456] Updater control panel changed location
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
Labels: backport

#458 [10.9] [PR 456] Updater control panel changed location
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
Labels: backport

#459 Added documentation how to pass the workgroup name
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#461 Removed /var/www/owncloud/occ
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
Labels: admin docs

#466 [10.10] [PR 461] Removed /var/www/owncloud/occ
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
Labels: backport

#467 [10.9] [PR 461] Removed /var/www/owncloud/occ
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
Labels: backport

#463 [10.9] [PR 459] Added documentation how to pass the workgroup name
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#462 [10.10] [PR 459] Added documentation how to pass the workgroup name
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#465 [10.9] [PR 460] Added description of password-from-service-account
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#464 [10.10] [PR 460] Added description of password-from-service-account
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#468 Improve upgrade script and text
  modules/admin_manual/examples/installation/manual_installation/instance.sh
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
Labels: admin docs

#469 [10.10] [PR 468] Improve upgrade script and text
  modules/admin_manual/examples/installation/manual_installation/instance.sh
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
Labels: backport

#470 [10.9] [PR 468] Improve upgrade script and text
  modules/admin_manual/examples/installation/manual_installation/instance.sh
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
Labels: backport

#473 [10.10] [PR 472] Removed php from occ calls
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/developer_manual/pages/scripts/theme-bootstrap.sh
  site.yml
Labels: backport

#474 [10.9] [PR 472] Removed php from occ calls
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/developer_manual/pages/scripts/theme-bootstrap.sh
  site.yml
Labels: backport

#480 Config-to-docs run to include new config elements coming from core
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#478 Fixing that occ needs to be set to executable if not already done.
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: admin docs

#481 [10.10] [PR 478] Fixing that occ needs to be set to executable if not already done.
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#482 [10.9] [PR 478] Fixing that occ needs to be set to executable if not already done.
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#477 Updated section about encryption overhead
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: admin docs

#476 Corrected upper and lower case
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: admin docs

#485 [10.10] [PR 476] Corrected upper and lower case
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: backport

#486 [10.9] [PR 476] Corrected upper and lower case
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: backport

#484 [10.9] [PR 477] Updated section about encryption overhead
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#483 [10.10] [PR 477] Updated section about encryption overhead
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#487 [10.10] [PR 475] Corrected rewrite rule
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#488 [10.9] [PR 475] Corrected rewrite rule
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#490 [10.10] [PR 489] Relocate some pages so that they naturally fit into the flow
  modules/admin_manual/pages/configuration/files/mimetypes.adoc
  modules/admin_manual/pages/configuration/general_topics/index.adoc
  modules/admin_manual/pages/configuration/general_topics/search.adoc
  modules/admin_manual/pages/configuration/mimetypes/index.adoc
  modules/admin_manual/pages/troubleshooting/general_troubleshooting.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#491 [10.9] [PR 489] Relocate some pages so that they naturally fit into the flow
  modules/admin_manual/pages/configuration/files/mimetypes.adoc
  modules/admin_manual/pages/configuration/general_topics/index.adoc
  modules/admin_manual/pages/configuration/general_topics/search.adoc
  modules/admin_manual/pages/configuration/mimetypes/index.adoc
  modules/admin_manual/pages/troubleshooting/general_troubleshooting.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#493 [10.10] [PR 492] Update the Virus Scanner page
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#494 [10.9] [PR 492] Update the Virus Scanner page
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#495 Update jQuery warnings page
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: admin docs

#496 [10.10] [PR 495] Update jQuery warnings page
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: backport

#497 [10.9] [PR 495] Update jQuery warnings page
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: backport
