Repository owncloud/docs-server, pull requests merged in 2022-03, with the labels that each got.

#124 [10.9] [PR 123] fix occ usage on qnap
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#125 [10.8] [PR 123] fix occ usage on qnap
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#128 Source language fix for harden server
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: admin docs

#129 Source language fix for MS Teams
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: admin docs

#130 [10.9] [PR 128] Source language fix for harden server
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#131 [10.8] [PR 128] Source language fix for harden server
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#132 [10.9] [PR 129] Source language fix for MS Teams
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: backport

#139 Set the correct source language for docker install
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#137 [10.9] [PR 133] Updates to innodb tunning instructions,
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
Labels: backport

#138 [10.8] [PR 133] Updates to innodb tunning instructions,
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
Labels: backport

#136 [10.8] [PR 134] Update update.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
Labels: backport

#135 [master] [PR 134] Update update.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
Labels: backport

#142 More Source Language Fixes
  modules/admin_manual/examples/installation/custom-app-directory-configuration.php
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/files/trashbin_options.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_oauth2_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
  modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
  modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/admin_manual/pages/faq/index.adoc
  modules/admin_manual/pages/found_a_mistake.adoc
  modules/admin_manual/pages/installation/changing_the_web_route.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/selinux_configuration.adoc
  modules/admin_manual/pages/installation/troubleshooting.adoc
  modules/admin_manual/pages/qnap/index.adoc
  modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc
Labels: admin docs

#143 [10.9] [PR 142] More Source Language Fixes
  modules/admin_manual/examples/installation/custom-app-directory-configuration.php
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/files/trashbin_options.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_oauth2_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
  modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
  modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/admin_manual/pages/faq/index.adoc
  modules/admin_manual/pages/found_a_mistake.adoc
  modules/admin_manual/pages/installation/changing_the_web_route.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/selinux_configuration.adoc
  modules/admin_manual/pages/installation/troubleshooting.adoc
  modules/admin_manual/pages/qnap/index.adoc
  modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc
Labels: backport

#144 [10.8] [PR 142] More Source Language Fixes
  modules/admin_manual/examples/installation/custom-app-directory-configuration.php
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/files/trashbin_options.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
  modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
  modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/admin_manual/pages/faq/index.adoc
  modules/admin_manual/pages/found_a_mistake.adoc
  modules/admin_manual/pages/installation/changing_the_web_route.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/selinux_configuration.adoc
  modules/admin_manual/pages/installation/troubleshooting.adoc
  modules/admin_manual/pages/qnap/index.adoc
  modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc
Labels: backport

#148 Fix typo
  modules/admin_manual/pages/appliance/configuration/index.php-less_URLs.adoc
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/appliance/maintenance/backup.adoc
  modules/admin_manual/pages/appliance/maintenance/howto-update-owncloud.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Labels: admin docs

#149 [10.9] [PR 148] Fix typo
  modules/admin_manual/pages/appliance/configuration/index.php-less_URLs.adoc
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/appliance/maintenance/backup.adoc
  modules/admin_manual/pages/appliance/maintenance/howto-update-owncloud.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Labels: backport

#150 [10.8] [PR 148] Fix typo
  modules/admin_manual/pages/appliance/configuration/index.php-less_URLs.adoc
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/appliance/maintenance/backup.adoc
  modules/admin_manual/pages/appliance/maintenance/howto-update-owncloud.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Labels: backport

#151 Inactivate the user guide
  modules/ROOT/partials/nav.adoc
  site.yml
Labels: deployment

#152 [10.9] [PR 151] Inactivate the user guide
  modules/ROOT/partials/nav.adoc
  site.yml
Labels: backport

#153 [10.8] [PR 151] Inactivate the user guide
  modules/ROOT/partials/nav.adoc
  site.yml
Labels: backport

#157 Fix some broken links found after migrating the user manual
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/partials/maintenance/major_release_note.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
Labels: admin docs, developer docs

#158 [10.9] [PR 157] Fix some broken links found after migrating the user manual
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/partials/maintenance/major_release_note.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
Labels: backport

#159 [10.8] [PR 157] Fix some broken links found after migrating the user manual
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/partials/maintenance/major_release_note.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
Labels: backport

#160 Correct system requirement text for 10.8 only
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: admin docs

#161 Broken internal link fix
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: admin docs

#162 [10.9] [PR 161] Broken internal link fix
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: backport

#163 [10.8] [PR 161] Broken internal link fix
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: backport

#166 [10.8] [PR 164] fix: replace outdated wopi docs urls
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#165 [10.9] [PR 164] fix: replace outdated wopi docs urls
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#170 [10.8] [PR 167] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#169 [10.9] [PR 167] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#171 [10.9] [PR 168] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#172 [10.8] [PR 168] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#174 [10.9] [PR 173] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#175 [10.8] [PR 173] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#176 Fix external URL links resulting in 404
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: bug

#177 [10.9] [PR 176] Fix external URL links resulting in 404
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#178 [10.8] [PR 176] Fix external URL links resulting in 404
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#179 [10.8] Fix broken link for 10.8 only
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
Labels: admin docs

#180 Small text improvement for the linux database configuration document
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Labels: admin docs

#181 [10.9] [PR 180] Small text improvement for the linux database configuration document
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Labels: backport

#182 [10.8] [PR 180] Small text improvement for the linux database configuration document
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Labels: backport

#183 Remove blank
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Labels: admin docs

#187 [10.9] [PR 185] expand install hints for postgresql (a bit)
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
Labels: backport

#188 [10.8] [PR 185] expand install hints for postgresql (a bit)
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
Labels: backport

#190 Define the correct oci8 release for pecl because of PHP7.x
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
Labels: admin docs

#192 [10.9] [PR 190] Define the correct oci8 release for pecl because of PHP7.x
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
Labels: backport

#194 [10.9] [PR 191] link to \"this guide\" added.
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
Labels: backport

#195 [10.8] [PR 191] link to \"this guide\" added.
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
Labels: backport

#189 Revision of the occ maintenance command description
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
Labels: admin docs

#196 [10.9] [PR 189] Revision of the occ maintenance command description
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
Labels: backport

#197 [10.8] [PR 189] Revision of the occ maintenance command description
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
Labels: backport

#198 Fix links to branded clients URL
  modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc
Labels: admin docs

#199 [10.9] [PR 198] Fix links to branded clients URL
  modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc
Labels: backport

#200 [10.8] [PR 198] Fix links to branded clients URL
  modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc
Labels: backport

#202 Prepare quoted text to be Antora 3 compliant
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: admin docs

#203 [10.9] [PR 202] Prepare quoted text to be Antora 3 compliant
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: backport

#204 [10.8] [PR 202] Prepare quoted text to be Antora 3 compliant
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: backport

#207 [10.9] [PR 206] Add support for pgsql 11 12 13 14
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#208 [10.9] [PR 205] onedrive app is not a standard enterprise app
  modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
Labels: backport

#214 [10.8] [PR 211] Update oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
Labels: backport

#213 [10.9] [PR 211] Update oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
Labels: backport

#215 [10.9] [PR 212] More improvements for quick installation guide
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#216 [10.8] [PR 212] More improvements for quick installation guide
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#217 add secure passwords
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#218 [10.9] [PR 217] add secure passwords
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#219 [10.8] [PR 217] add secure passwords
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#220 Fixed headline capitalization
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#221 [10.9] [PR 220] Fixed headline capitalization
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#222 [10.8] [PR 220] Fixed headline capitalization
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#231 [10.8] [PR 227] Update system_requirements.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#230 [10.9] [PR 227] Update system_requirements.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport
