Repository owncloud/docs-server, pull requests merged in 2022-02, with the labels that each got.

#32 [10.9] [PR 30] mpm_event conflicts with php
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  site.yml
Labels: backport

#33 [10.8] [PR 30] mpm_event conflicts with php
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  site.yml
Labels: backport

#34 Config-to-docs Run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#35 [10.9] [PR 34] Config-to-docs Run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#41 Fix docker compose example link
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#42 [10.9] [PR 41] Fix docker compose example link
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#43 [10.8] [PR 41] Fix docker compose example link
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#45 [10.9] [PR 44] Update naming
  antora.yml
  modules/ROOT/pages/index.adoc
  modules/ROOT/partials/nav.adoc
  modules/admin_manual/pages/index.adoc
  modules/developer_manual/pages/index.adoc
Labels: backport

#47 Fix the resource coordinates in the introduction
  modules/ROOT/pages/index.adoc
Labels: deployment

#49 [10.8] [PR 47] Fix the resource coordinates in the introduction
  modules/ROOT/pages/index.adoc
Labels: backport

#52 [10.8] only - fix version in antora.yml
  antora.yml
Labels: deployment

#53 [master] [PR 50] Remove mistake entry about incompatibility with storage encryption
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#54 Fix broken antora component links to docs
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  site.yml
Labels: deployment

#56 [10.8] [PR 54] Fix broken antora component links to docs
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  site.yml
Labels: backport

#55 [10.9] [PR 54] Fix broken antora component links to docs
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  site.yml
Labels: backport

#59 Update manual upgrade documentation
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
  site.yml
Labels: admin docs

#61 [10.9] [PR 60] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#62 [10.8] [PR 60] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#64 [10.8] [PR 59] Update manual upgrade documentation
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
  site.yml
Labels: backport

#67 [10.9] [PR 65] Fix complete bundle name
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#68 [10.8] [PR 65] Fix complete bundle name
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#69 Dev: rename {examplesdir} with example$
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/fundamentals/filesystem.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
  modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
  modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/apis/ocs-user-sync-api.adoc
  modules/developer_manual/pages/core/apis/roles-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/general/backporting.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
  modules/developer_manual/pages/webdav_api/public_files.adoc
  modules/developer_manual/pages/webdav_api/search/_filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/_search_files.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
  modules/developer_manual/partials/webdav_api/files_versions/list_files_versions.adoc
  modules/developer_manual/partials/webdav_api/search/common_error_responses.adoc
Labels: developer docs

#70 Admin: rename {examplesdir} with example$
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#71 [10.9] [PR 69] Dev: rename {examplesdir} with example$
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/fundamentals/filesystem.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
  modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
  modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/apis/ocs-user-sync-api.adoc
  modules/developer_manual/pages/core/apis/roles-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/general/backporting.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
  modules/developer_manual/pages/webdav_api/public_files.adoc
  modules/developer_manual/pages/webdav_api/search/_filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/_search_files.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
  modules/developer_manual/partials/webdav_api/files_versions/list_files_versions.adoc
  modules/developer_manual/partials/webdav_api/search/common_error_responses.adoc
Labels: backport

#72 [10.8] [PR 69] Dev: rename {examplesdir} with example$
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/fundamentals/filesystem.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
  modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
  modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/apis/ocs-user-sync-api.adoc
  modules/developer_manual/pages/core/apis/roles-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/general/backporting.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
  modules/developer_manual/pages/webdav_api/public_files.adoc
  modules/developer_manual/pages/webdav_api/search/_filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/_search_files.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
  modules/developer_manual/partials/webdav_api/files_versions/list_files_versions.adoc
  modules/developer_manual/partials/webdav_api/search/common_error_responses.adoc
Labels: backport

#73 [10.9] [PR 70] Admin: rename {examplesdir} with example$
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#74 [10.8] [PR 70] Admin: rename {examplesdir} with example$
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#76 Remove ondrej remnants and fix WND
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#79 [10.8] [PR 76] Remove ondrej remnants and fix WND
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#78 [10.9] [PR 76] Remove ondrej remnants and fix WND
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#81 Dev: rename {partialsdir} with partial$
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/core/apis/index.adoc
  modules/developer_manual/pages/testing/index.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/index.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
  modules/developer_manual/pages/webdav_api/search/_filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/_search_files.adoc
Labels: developer docs

#83 [10.9] [PR 81] Dev: rename {partialsdir} with partial$
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/core/apis/index.adoc
  modules/developer_manual/pages/testing/index.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/index.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
  modules/developer_manual/pages/webdav_api/search/_filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/_search_files.adoc
Labels: backport

#82 Admin: rename {partialsdir} with partial$
  modules/admin_manual/pages/appliance/configuration/index.adoc
  modules/admin_manual/pages/appliance/maintenance/index.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/external_storage/index.adoc
  modules/admin_manual/pages/configuration/server/index.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
  modules/admin_manual/pages/configuration/user/reset_user_password.adoc
  modules/admin_manual/pages/enterprise/clients/index.adoc
  modules/admin_manual/pages/enterprise/collaboration/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/index.adoc
  modules/admin_manual/pages/enterprise/file_management/index.adoc
  modules/admin_manual/pages/enterprise/firewall/index.adoc
  modules/admin_manual/pages/enterprise/logging/index.adoc
  modules/admin_manual/pages/enterprise/reporting/index.adoc
  modules/admin_manual/pages/enterprise/security/index.adoc
  modules/admin_manual/pages/enterprise/server_branding/index.adoc
  modules/admin_manual/pages/enterprise/user_management/index.adoc
  modules/admin_manual/pages/installation/apps/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
  modules/admin_manual/pages/troubleshooting/index.adoc
Labels: admin docs

#86 [10.9] [PR 82] Admin: rename {partialsdir} with partial$
  modules/admin_manual/pages/appliance/configuration/index.adoc
  modules/admin_manual/pages/appliance/maintenance/index.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/external_storage/index.adoc
  modules/admin_manual/pages/configuration/server/index.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
  modules/admin_manual/pages/configuration/user/reset_user_password.adoc
  modules/admin_manual/pages/enterprise/clients/index.adoc
  modules/admin_manual/pages/enterprise/collaboration/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/index.adoc
  modules/admin_manual/pages/enterprise/file_management/index.adoc
  modules/admin_manual/pages/enterprise/firewall/index.adoc
  modules/admin_manual/pages/enterprise/logging/index.adoc
  modules/admin_manual/pages/enterprise/reporting/index.adoc
  modules/admin_manual/pages/enterprise/security/index.adoc
  modules/admin_manual/pages/enterprise/server_branding/index.adoc
  modules/admin_manual/pages/enterprise/user_management/index.adoc
  modules/admin_manual/pages/installation/apps/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
  modules/admin_manual/pages/troubleshooting/index.adoc
Labels: backport

#87 [10.8] [PR 82] Admin: rename {partialsdir} with partial$
  modules/admin_manual/pages/appliance/configuration/index.adoc
  modules/admin_manual/pages/appliance/maintenance/index.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/external_storage/index.adoc
  modules/admin_manual/pages/configuration/server/index.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
  modules/admin_manual/pages/configuration/user/reset_user_password.adoc
  modules/admin_manual/pages/enterprise/clients/index.adoc
  modules/admin_manual/pages/enterprise/collaboration/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/index.adoc
  modules/admin_manual/pages/enterprise/file_management/index.adoc
  modules/admin_manual/pages/enterprise/firewall/index.adoc
  modules/admin_manual/pages/enterprise/logging/index.adoc
  modules/admin_manual/pages/enterprise/reporting/index.adoc
  modules/admin_manual/pages/enterprise/security/index.adoc
  modules/admin_manual/pages/enterprise/server_branding/index.adoc
  modules/admin_manual/pages/enterprise/user_management/index.adoc
  modules/admin_manual/pages/installation/apps/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
  modules/admin_manual/pages/troubleshooting/index.adoc
Labels: backport

#80 Fix and improve the install and upgrade guides
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/index.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/index.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/partials/maintenance/major_release_note.adoc
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#88 [10.9] [PR 80] Fix and improve the install and upgrade guides
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/index.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/index.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/partials/maintenance/major_release_note.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#89 [10.8] [PR 80] Fix and improve the install and upgrade guides
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/index.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/index.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/partials/maintenance/major_release_note.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#90 Shift the wizard location by one to the left
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#91 [10.9] [PR 90] Shift the wizard location by one to the left
  modules/admin_manual/partials/nav.adoc
Labels: backport

#92 [10.8] [PR 90] Shift the wizard location by one to the left
  modules/admin_manual/partials/nav.adoc
Labels: backport

#97 [10.8] [PR 95] Include the PHP version in the Requirements cell referenced in upgrade.adoc
  modules/admin_manual/partials/maintenance/major_release_note.adoc
Labels: backport

#96 [10.9] [PR 95] Include the PHP version in the Requirements cell referenced in upgrade.adoc
  modules/admin_manual/partials/maintenance/major_release_note.adoc
Labels: backport

#98 Fix the main installation overview document
  modules/admin_manual/pages/installation/index.adoc
Labels: admin docs

#100 [10.8] [PR 98] Fix the main installation overview document
  modules/admin_manual/pages/installation/index.adoc
Labels: backport

#102 [10.9] [PR 75] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#104 deleting orphans
  modules/admin_manual/examples/installation/ubuntu/18.04/configure-log-rotation.sh
  modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
Labels: admin docs

#105 [10.9] [PR 104] deleting orphans
  modules/admin_manual/examples/installation/ubuntu/18.04/configure-log-rotation.sh
  modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
Labels: backport

#103 [10.8] [PR 75] Update ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#108 [10.8] [PR 106] Update manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#107 [10.9] [PR 106] Update manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#115 [10.8] [PR 113] Ubuntu 20.04 Quick Guide improvements
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#114 [10.9] [PR 113] Ubuntu 20.04 Quick Guide improvements
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#120 finalise typo
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#119 [10.8] [PR 117] Enable encryption via occ is incomplete and leads to deprecated user-key mode
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#118 [10.9] [PR 117] Enable encryption via occ is incomplete and leads to deprecated user-key mode
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#121 [10.8] [PR 120] finalise typo
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport
