Repository owncloud/docs-server, pull requests merged in 2022-09, with the labels that each got.

#595 Update activity app
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
Labels: admin docs

#597 [10.9] [PR 595] Update activity app
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
Labels: backport

#600 Add recent core changes
  modules/admin_manual/images/configuration/files/files_versions/concious-persistent-major-versions.png
  modules/admin_manual/images/configuration/files/files_versions/files-versions.png
  modules/admin_manual/pages/configuration/files/file_versioning.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
  modules/admin_manual/pages/gdpr.adoc
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#601 Config to docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#603 [10.9] [PR 548] User counting
  modules/admin_manual/pages/enterprise/installation/install.adoc
Labels: backport

#606 [master] [PR 599] Update ubuntu_22_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
Labels: backport

#605 [10.9] [PR 599] Update ubuntu_22_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
Labels: backport

#602 Secure View update
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#604 [master] [PR 548] User counting
  modules/admin_manual/pages/enterprise/installation/install.adoc
Labels: backport

#607 Fix Impersonate not working with Shibboleth
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: admin docs

#608 [10.10] [PR 607] Fix Impersonate not working with Shibboleth
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#609 [10.9] [PR 607] Fix Impersonate not working with Shibboleth
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#611 Custom Groups
  modules/admin_manual/images/configuration/user/custom_groups/custom_groups.png
  modules/admin_manual/images/configuration/user/custom_groups/user_settings_custom_groups.png
  modules/admin_manual/images/custom-groups/owncloud-market-custom-groups-install.png
  modules/admin_manual/images/custom-groups/owncloud-market-custom-groups.png
  modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#612 Fix in-page link
  modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
Labels: admin docs

#613 Updating the guests app
  modules/admin_manual/images/configuration/user/guest_app/guest_app_settings.png
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: admin docs

#614 [10.10] [PR 613] Updating the guests app
  modules/admin_manual/images/configuration/user/guest_app/guest_app_settings.png
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: backport

#615 [10.9] [PR 613] Updating the guests app
  modules/admin_manual/images/configuration/user/guest_app/guest_app_settings.png
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: backport

#616 Changes necessary for 10.11
  .drone.star
  site.yml
Labels: deployment

#617 occ previews:cleanup
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
Labels: admin docs

#618 [10.11] [PR 617] occ previews:cleanup
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
Labels: backport

#620 Fix occ preview command
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
Labels: admin docs

#619 Fix occ source block
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs

#622 [10.10] [PR 619] Fix occ source block
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#624 Move occ system commands to the correct location
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_system_command.adoc
Labels: admin docs

#626 [10.10] [PR 624] Move occ system commands to the correct location
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_system_command.adoc
Labels: backport

#629 [10.11] [PR 628] Update local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
Labels: backport

#630 [10.10] [PR 628] Update local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
Labels: backport

#631 [10.9] [PR 628] Update local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
Labels: backport

#634 Update Impersonate
  modules/admin_manual/images/apps/impersonate/impersonate-settings.png
  modules/admin_manual/images/apps/impersonate/limit-impersonation-to-specific-groups.png
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: admin docs

#635 [10.11] [PR 634] Update Impersonate
  modules/admin_manual/images/apps/impersonate/impersonate-settings.png
  modules/admin_manual/images/apps/impersonate/limit-impersonation-to-specific-groups.png
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#636 [10.10] [PR 634] Update Impersonate
  modules/admin_manual/images/apps/impersonate/impersonate-settings.png
  modules/admin_manual/images/apps/impersonate/limit-impersonation-to-specific-groups.png
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#637 [10.9] [PR 634] Update Impersonate
  modules/admin_manual/images/apps/impersonate/impersonate-settings.png
  modules/admin_manual/images/apps/impersonate/limit-impersonation-to-specific-groups.png
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#638 Config-to-docs Update
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#639 [10.11] [PR 638] Config-to-docs Update
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#640 Update the Customgroups image
  modules/admin_manual/images/configuration/user/custom_groups/user_settings_custom_groups.png
Labels: admin docs

#641 [10.11] [PR 640] Update the Customgroups image
  modules/admin_manual/images/configuration/user/custom_groups/user_settings_custom_groups.png
Labels: backport

#643 [10.11] [PR 642] update impersonate
  modules/admin_manual/images/apps/impersonate/impersonate-settings.png
  modules/admin_manual/images/apps/impersonate/impersonate_group_admins_only.png
  modules/admin_manual/images/apps/impersonate/impersonate_groups_only.png
  modules/admin_manual/images/apps/impersonate/impersonate_oc_admins_only.png
  modules/admin_manual/images/apps/impersonate/limit-impersonation-to-specific-groups.png
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#647 Preview cleanup update
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
Labels: admin docs

#648 [10.11] [PR 647] Preview cleanup update
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_previews_commands.adoc
Labels: backport

#646 occ commands for Impersonate
  modules/admin_manual/images/apps/impersonate/impersonate_enable.png
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
Labels: admin docs

#649 [10.11] [PR 646] occ commands for Impersonate
  modules/admin_manual/images/apps/impersonate/impersonate_enable.png
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
Labels: backport

#652 [10.11] [PR 650] Add the supported database connectors to docker install
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#653 [10.10] [PR 650] Add the supported database connectors to docker install
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#651 Adjust text and examples for setting up the Impersonate app
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: admin docs

#654 [10.11] [PR 651] Adjust text and examples for setting up the Impersonate app
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#656 [10.11] [PR 655] Small addition to #650
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#657 [10.10] [PR 655] Small addition to #650
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#658 doc update for owncloud/core#40389
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: admin docs

#659 [10.11] [PR 658] doc update for owncloud/core#40389
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#660 [10.10] [PR 658] doc update for owncloud/core#40389
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport
