Repository owncloud/docs-server, pull requests merged in 2023-11, with the labels that each got.

#1115 Update Full Text Search because of RelevanceV2
  modules/admin_manual/images/apps/search_elastic/connector_setup.png
  modules/admin_manual/pages/configuration/general_topics/search.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_full_text_search_commands.adoc
Labels: admin docs

#1156 [10.13] [PR 1155] Update manually-moving-data-folders.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#1157 [10.12] [PR 1155] Update manually-moving-data-folders.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#1159 [10.12] [PR 1115] Update Full Text Search because of RelevanceV2
  modules/admin_manual/images/apps/search_elastic/connector_setup.png
  modules/admin_manual/pages/configuration/general_topics/search.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_full_text_search_commands.adoc
Labels: backport

#1163 [10.13] [PR 1160] Update manually-moving-data-folders.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#1164 [10.12] [PR 1160] Update manually-moving-data-folders.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#1165 [10.13] [PR 1152] improve/fix manually-moving-data-folders.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#1166 [10.12] [PR 1152] improve/fix manually-moving-data-folders.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#1172 [10.12] [PR 1169] Update collabora_secure_view.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#1171 [master] [PR 1169] Update collabora_secure_view.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#1177 [10.13] [PR 1174] Update appliance installation.adoc
  modules/admin_manual/pages/appliance/installation/installation.adoc
Labels: backport

#1180 [10.12] [PR 1175] Update appliance configuration login_information.adoc
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
Labels: backport

#1181 [10.13] [PR 1176] Update appliance firewall.adoc
  modules/admin_manual/pages/appliance/configuration/firewall.adoc
Labels: backport

#1182 [10.12] [PR 1176] Update appliance firewall.adoc
  modules/admin_manual/pages/appliance/configuration/firewall.adoc
Labels: backport

#1185 Updates config.sample and some docker related text
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#1186 [10.12] PR 1185] Updates config.sample and some docker related text
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#1187 [10.13] [PR 1185] Updates config.sample and some docker related text
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#1188 [10.13] [PR 1183] Update occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#1189 [10.12] [PR 1183] Update occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#1190 Config-to-Docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: documentation

#1192 [10.13] [PR 1190] Config-to-Docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#1191 [10.12] [PR 1190] Config-to-Docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#1193 Another necessary config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#1194 [10.12] [PR 1193] Another necessary config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#1195 [10.13] [PR 1193] Another necessary config to docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#1201 Update readme and prepare dev env
  .gitignore
  README.md
  bin/prepare_site_yml
Labels: deployment

#1202 [10.12] [PR 1201] Update readme and prepare dev env
  .gitignore
  README.md
  bin/prepare_site_yml
Labels: backport

#1203 [10.13] [PR 1201] Update readme and prepare dev env
  .gitignore
  README.md
  bin/prepare_site_yml
Labels: backport

#1204 Update package.json
  package.json
Labels: deployment

#1205 [10.12] [PR 1204] Update package.json
  package.json
Labels: backport

#1206 [10.13] [PR 1204] Update package.json
  package.json
Labels: backport
