Repository owncloud/docs-server, pull requests merged in 2023-12, with the labels that each got.

#1210 [10.13] [PR 1209] Update WND and Kerberos
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  modules/admin_manual/images/configuration/files/external_storage/external-storage-dropbox-highlighted.png
  modules/admin_manual/images/configuration/files/external_storage/google_drive/003.png
  modules/admin_manual/images/enterprise/authentication/enterprise-only-auth/auth_backends-1.png
  modules/admin_manual/images/enterprise/authentication/enterprise-only-auth/authentication-backends.png
  modules/admin_manual/images/enterprise/authentication/enterprise-only-auth/global-credentials.png
  modules/admin_manual/images/enterprise/authentication/kerberos/kerberos-win-principal.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-1.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-2.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-3.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-available-for.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-config-key.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-gear-icon.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-kerberos-1.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-kerberos-2.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-username-pwd.png
  modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
  modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
  modules/admin_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
  modules/admin_manual/pages/configuration/files/external_storage/sftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
  modules/admin_manual/pages/configuration/files/external_storage/webdav.adoc
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/enterprise/authentication/enterprise_only_auth.adoc
  modules/admin_manual/pages/enterprise/authentication/kerberos.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/partials/installation/manual_installation/useful_tips.adoc
Labels: backport

#1211 [10.12] [PR 1209] Update WND and Kerberos
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  modules/admin_manual/images/configuration/files/external_storage/external-storage-dropbox-highlighted.png
  modules/admin_manual/images/configuration/files/external_storage/google_drive/003.png
  modules/admin_manual/images/enterprise/authentication/enterprise-only-auth/auth_backends-1.png
  modules/admin_manual/images/enterprise/authentication/enterprise-only-auth/authentication-backends.png
  modules/admin_manual/images/enterprise/authentication/enterprise-only-auth/global-credentials.png
  modules/admin_manual/images/enterprise/authentication/kerberos/kerberos-win-principal.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-1.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-2.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-3.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-available-for.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-config-key.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-gear-icon.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-kerberos-1.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-kerberos-2.png
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-username-pwd.png
  modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
  modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
  modules/admin_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
  modules/admin_manual/pages/configuration/files/external_storage/sftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
  modules/admin_manual/pages/configuration/files/external_storage/webdav.adoc
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/enterprise/authentication/enterprise_only_auth.adoc
  modules/admin_manual/pages/enterprise/authentication/kerberos.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/partials/installation/manual_installation/useful_tips.adoc
Labels: backport

#1212 Update site.yml
  site.yml
Labels: deployment

#1213 [10.12] [PR 1212] Update site.yml
  site.yml
Labels: backport

#1214 [10.13] [PR 1212] Update site.yml
  site.yml
Labels: backport

#1216 limit 'chosen freely' in windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#1217 [10.12] [PR 1216] limit 'chosen freely' in windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#1218 [10.13] [PR 1216] limit 'chosen freely' in windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport
