Repository owncloud/docs-server, pull requests merged in 2023-04, with the labels that each got.

#922 [10.11] [PR 921] changed the medium deployment recommendations based …
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: backport

#923 [10.12] [PR 921] changed the medium deployment recommendations based …
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: backport

#930 [10.11] [PR 928] Remove out-of-date Travis mentions
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/.travis.yml
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/README.md
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/promises/.travis.yml
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/.travis.yml
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/README.md
Labels: backport

#931 [10.12] [PR 928] Remove out-of-date Travis mentions
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/.travis.yml
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/README.md
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/promises/.travis.yml
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/.travis.yml
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/README.md
Labels: backport

#932 [10.11] [PR 929] Update ui-testing to have current content
  modules/developer_manual/pages/testing/ui-testing.adoc
Labels: backport

#933 [10.12] [PR 929] Update ui-testing to have current content
  modules/developer_manual/pages/testing/ui-testing.adoc
Labels: backport

#935 [10.11] [PR 934] added instructions how to enable legacy support
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
Labels: backport

#943 [10.12] [PR 941] Changed order of pear & php-alternatives
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
Labels: backport

#944 [10.11] [PR 941] Changed order of pear & php-alternatives
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
Labels: backport

#947 [10.12] [PR 946] added enabling of ssl module to apache ssl configuration
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: backport

#948 [10.11] [PR 946] added enabling of ssl module to apache ssl configuration
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: backport

#950 [10.12] [PR 949] Change old references from PHP 7.3 to 7.4
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_22.04.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
Labels: backport

#952 Update collabora_secure_view.adoc [10.11.0]
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#954 Add a new ocis attribute to site.yml
  site.yml
Labels: documentation

#957 added redirect permanent configuration
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: documentation

#958 [10.11] [PR 957] added redirect permanent configuration
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
Labels: backport

#961 [10.11] [PR 939] Document Desktop, Android and iOS app default scope and prompt parameters
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#966 Update federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: admin docs

#970 [10.12] [PR 969] layout fix for PR966
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#971 [10.11] [PR 969] layout fix for PR966
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport
