Repository owncloud/docs-server, pull requests merged in 2023-07, with the labels that each got.

#1018 Update system_requirements, use MariaDB 10.11 as default
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: documentation

#1020 Remove youtube community channel
  modules/admin_manual/pages/index.adoc
Labels: documentation

#1021 Update oidc.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: admin docs

#1023 [10.11] [PR 1018] Update system_requirements, use MariaDB 10.11 as default
  .drone.star
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#1024 [10.12] [PR 1018] Update system_requirements, use MariaDB 10.11 as default
  .drone.star
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#1026 [10.12] [PR 1021] Update oidc.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#1025 [10.11] [PR 1021] Update oidc.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#1027 [10.11] [PR 1020] Remove youtube community channel
  modules/admin_manual/pages/index.adoc
Labels: backport

#1028 [10.12] [PR 1020] Remove youtube community channel
  modules/admin_manual/pages/index.adoc
Labels: backport

#1031 Config to Docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#1030 Fix syntax of mail_smtpdebug example
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: admin docs

#1032 [10.11] [PR 1030] Fix syntax of mail_smtpdebug example
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: backport

#1033 [10.12] [PR 1030] Fix syntax of mail_smtpdebug example
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: backport

#1035 [10.11] [PR 1017] Added some hints how to survive the trusted_domains issue with docker
  modules/admin_manual/pages/maintenance/migrating.adoc
Labels: backport

#1034 [master] [PR 1017] Added some hints how to survive the trusted_domains issue with docker
  modules/admin_manual/pages/maintenance/migrating.adoc
Labels: backport

#1040 Update site.yml
  site.yml
Labels: deployment

#1041 [10.11] [PR 1040] Update site.yml
  site.yml
Labels: backport

#1042 [10.12] [PR 1040] Update site.yml
  site.yml
Labels: backport

#1045 Added MARIADB_AUTO_UPGRADE=1
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
Labels: admin docs

#1046 [10.11] [PR 1045] Added MARIADB_AUTO_UPGRADE=1
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
Labels: backport

#1047 [10.12] [PR 1045] Added MARIADB_AUTO_UPGRADE=1
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
Labels: backport

#1049 [10.12] [PR 1037] Update impersonate_users.adoc
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#1050 [10.11] [PR 1038] Update impersonate_users.adoc opendconnect works
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#1051 [10.12] [PR 1038] Update impersonate_users.adoc opendconnect works
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
Labels: backport

#1053 [10.11] [PR 1052] Document data exporter 236 last login timestamp behavior
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_exporter_commands.adoc
  modules/admin_manual/pages/maintenance/export_import_instance_data.adoc
Labels: backport

#1054 [10.12] [PR 1052] Document data exporter 236 last login timestamp behavior
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_exporter_commands.adoc
  modules/admin_manual/pages/maintenance/export_import_instance_data.adoc
Labels: backport
