Repository owncloud/docs-server, pull requests merged in 2023-08, with the labels that each got.

#1057 Fix import name of occ cammand
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs

#1058 [10.11] [PR 1057] Fix import name of occ cammand
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#1062 [10.11] [PR 1060] Update user_roles.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
Labels: backport

#1068 Update the Docker Compose section
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#1069 [10.11] [PR 1068] Update the Docker Compose section
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#1070 [10.12] [PR 1068] Update the Docker Compose section
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#1071 Mini fix for docker compose
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#1072 [10.11] [PR 1071] Mini fix for docker compose
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#1073 [10.12] [PR 1071] Mini fix for docker compose
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#1075 Avoid Fairydust
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#1076 [10.11] [PR 1075] Avoid Fairydust
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#1079 [10.12] [PR 1078] Update federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#1080 [master] [PR 1078] Update federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#1081 [10.13] [PR 1078] Update federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#1082 Changes necessary for 10.13
  .drone.star
  site.yml
Labels: deployment

#1084 Revert "[10.12] [PR 1078] Update federated_cloud_sharing_configuration.adoc"
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#1083 Revert "Update federated_cloud_sharing_configuration.adoc"
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#1085 Revert "[master] [PR 1078] Update federated_cloud_sharing_configuration.adoc"
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#1087 Update federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: admin docs

#1090 Add new occ federation:trusted-servers
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_federation_trusted_servers.adoc
Labels: admin docs

#1091 [10.13] [PR 1090] Add new occ federation:trusted-servers
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_federation_trusted_servers.adoc
Labels: backport

#1093 [10.13] [PR 1092] Updated LDAP screenshots
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/advanced-tab-connection-settings.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/advanced-tab-directory-settings.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/advanced-tab-special-attributes.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/expert-tab.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/groups-tab.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/login-attributes-tab.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/server-tab.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/users-tab.png
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#1094 [10.12] [PR 1092] Updated LDAP screenshots
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/advanced-tab-connection-settings.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/advanced-tab-directory-settings.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/advanced-tab-special-attributes.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/expert-tab.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/groups-tab.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/login-attributes-tab.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/server-tab.png
  modules/admin_manual/images/apps/user_ldap/ldap-wizard/users-tab.png
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#1095 Update the WND page
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#1097 [10.12] [PR 1095] Update the WND page
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#1100 Update openssl
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
Labels: admin docs

#1101 [10.12] [PR 1100] Update openssl
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
Labels: backport

#1102 [10.13] [PR 1100] Update openssl
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
Labels: backport

#1103 Fix SQL commands when installing
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
  modules/admin_manual/partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#1104 [10.12] [PR 1103] Fix SQL commands when installing
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
  modules/admin_manual/partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#1105 [10.13] [PR 1103] Fix SQL commands when installing
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
  modules/admin_manual/partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport
