Repository owncloud/docs-server, pull requests merged in 2023-02, with the labels that each got.

#839 occ: Allow to Temporarily Ignore Invalid Federated Shares
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
Labels: admin docs

#841 Update Configure MySQL for 4-byte Unicode Support
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Labels: admin docs

#842 [10.11] [PR 841] Update Configure MySQL for 4-byte Unicode Support
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Labels: backport

#843 [10.10] [PR 841] Update Configure MySQL for 4-byte Unicode Support
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Labels: backport

#845 [10.10] [PR 844] Explain check-out, check-in by example
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
Labels: backport

#846 [10.11] [PR 844] Explain check-out, check-in by example
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
Labels: backport

#848 [10.10] [PR 847] Also mention user guide?
  modules/ROOT/pages/index.adoc
Labels: backport

#849 [10.11] [PR 847] Also mention user guide?
  modules/ROOT/pages/index.adoc
Labels: backport

#851 [10.10] [PR 850] add notice about ImageMagick's scripting language (MSL)
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#852 [10.11] [PR 850] add notice about ImageMagick's scripting language (MSL)
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#854 user:sync short form of backend classes
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: admin docs

#855 Changes necessary for 10.12
  .drone.star
  site.yml
Labels: deployment

#856 Update the new version branch documentation
  docs/new-version-branch.md
Labels: deployment

#860 Update S3 concurrency example
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: admin docs

#861 [10.10] [PR 860] Update S3 concurrency example
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#862 [10.11] [PR 860] Update S3 concurrency example
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#863 [10.12] [PR 860] Update S3 concurrency example
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport
