Repository owncloud/docs-server, pull requests merged in 2023-01, with the labels that each got.

#786 Create a Useful Pages page
  modules/admin_manual/pages/useful_pages.adoc
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#787 [10.10] [PR 786] Create a Useful Pages page
  modules/admin_manual/pages/useful_pages.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#788 [10.11] [PR 786] Create a Useful Pages page
  modules/admin_manual/pages/useful_pages.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#789 Add WOPI Business Flow
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: admin docs

#790 [10.11] [PR 789] Add WOPI Business Flow
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#791 [10.10] [PR 789] Add WOPI Business Flow
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#797 [master] [PR 795] Adding Additional Enterprise Apps
  modules/admin_manual/pages/installation/apps_supported.adoc
Labels: backport

#798 [10.10] [PR 795] Adding Additional Enterprise Apps
  modules/admin_manual/pages/installation/apps_supported.adoc
Labels: backport

#799 Update apps supported
  modules/admin_manual/pages/installation/apps_supported.adoc
Labels: admin docs

#800 [10.11] [PR 799] Update apps supported
  modules/admin_manual/pages/installation/apps_supported.adoc
Labels: backport

#801 [10.10] [PR 799] Update apps supported
  modules/admin_manual/pages/installation/apps_supported.adoc
Labels: backport

#803 [10.11] [PR 802] Update ubuntu_22_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
Labels: backport

#804 [10.10] [PR 802] Update ubuntu_22_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_22_04.adoc
Labels: backport

#810 Fixing the sort order of suggested commands in owncloud_prep.sh
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
Labels: admin docs

#811 [10.10] [PR 810] Fixing the sort order of suggested commands in owncl…
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
Labels: backport

#812 [10.11] [PR 810] Fixing the sort order of suggested commands in owncl…
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
Labels: backport

#813 [10.11] [PR 806] [OIDC] Branded desktop and mobile clients for Azure AD
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#814 [10.10] [PR 806] [OIDC] Branded desktop and mobile clients for Azure AD
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#815 Add note for updater app
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
Labels: admin docs

#817 [10.11] [PR 815] Add note for updater app
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
Labels: backport

#816 [10.10] [PR 815] Add note for updater app
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
Labels: backport

#820 New occ ransomware command
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: admin docs

#823 [10.11] [PR 819] wrong command named
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
Labels: backport

#824 [10.10] [PR 819] wrong command named
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
Labels: backport

#821 [10.11] [PR 820] New occ ransomware command
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: backport

#822 [10.10] [PR 820] New occ ransomware command
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ransomware_protection_commands.adoc
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: backport

#825 Config to Docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#826 Add Login Policies
  modules/admin_manual/pages/configuration/user/login_policies.adoc
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#827 Config-to-Docs run with fixes
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#829 [10.11] [PR 828] Hint for updated link names in onedrive.adoc
  modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
Labels: backport

#830 [10.10] [PR 828] Hint for updated link names in onedrive.adoc
  modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
Labels: backport

#832 Config-to-Docs run for changes in Core (oidc auto-provision)
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#833 [10.10] [PR 832] Config-to-Docs run for changes in Core (oidc auto-pr…
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#835 Update PHP minimum version
  antora.yml
Labels: documentation
