Repository owncloud/docs-server, pull requests merged in 2023-06, with the labels that each got.

#1002 Fix Broken Link
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
Labels: documentation

#1004 [10.12] [PR 1002] Fix Broken Link
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
Labels: backport

#1005 Fix missing image (10.11 only)
  modules/admin_manual/images/configuration/files/files_versions/concious-persistent-major-versions.png
  modules/admin_manual/images/configuration/files/files_versions/version-metadata.png
Labels: documentation

#1009 [10.12] [PR 1007] Update ms-azure-setup.adoc with oAuth2
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: backport

#1008 [10.11] [PR 1007] Update ms-azure-setup.adoc with oAuth2
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: backport

#1012 Add missing attributes in site.yml (local build relevant only)
  site.yml
Labels: deployment

#1011 Update configuration.adoc (how to remove orphand storage entries))
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: admin docs

#1014 [10.11] [PR 1012] Add missing attributes in site.yml (local build relevant only)
  site.yml
Labels: backport

#1015 [10.12] [PR 1012] Add missing attributes in site.yml (local build relevant only)
  site.yml
Labels: backport
