Repository owncloud/docs-server, pull requests merged in 2024-07, with the labels that each got.

#1336 More details for migrating_to_kiteworks.adoc
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: admin docs

#1345 [10.15] [PR 1336] More details for migrating_to_kiteworks.adoc
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: backport

#1344 [10.14] [PR 1336] More details for migrating_to_kiteworks.adoc
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: backport

#1348 Config to docs run based on recent config sample changes
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#1349 [10.15] [PR 1348] Config to docs run based on recent config sample changes
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#1353 Fix two build error messages in dev docs
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/general/codingguidelines.adoc
Labels: developer docs

#1354 [10.15] [PR 1353] Fix two build error messages in dev docs
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/general/codingguidelines.adoc
Labels: backport

#1355 [10.14] [PR 1353] Fix two build error messages in dev docs
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/general/codingguidelines.adoc
Labels: backport

#1356 [10.13] [PR 1353] Fix two build error messages in dev docs
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/general/codingguidelines.adoc
Labels: backport

#1357 Antora package.json refactoring
  package.json
  yarn.lock
Labels: dependencies

#1358 [10.15] [PR 1357] Antora package.json refactoring
  package.json
  yarn.lock
Labels: backport

#1359 [10.14] [PR 1357] Antora package.json refactoring
  package.json
  yarn.lock
Labels: backport
