Repository owncloud/docs-server, pull requests merged in 2024-06, with the labels that each got.

#1301 Fix command typo in generate-index.js
  ext-antora/generate-index.js
Labels: bug

#1306 [10.14] [PR 1299] clarify sharing bits
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#1307 [10.13] [PR 1299] clarify sharing bits
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#1311 [10.13] [PR 1229] Clarify and correct accounts table step
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#1308 [master] [PR 1225] Update installation.adoc
  modules/admin_manual/pages/appliance/installation/installation.adoc
Labels: backport

#1309 [10.14] [PR 1225] Update installation.adoc
  modules/admin_manual/pages/appliance/installation/installation.adoc
Labels: backport

#1310 [10.14] [PR 1229] Clarify and correct accounts table step
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#1312 [10.14] [PR 1298] Typo encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
Labels: backport

#1313 [10.13] [PR 1298] Typo encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
Labels: backport

#1316 [10.14] [PR 1222] Update WND Kerberos LDAP
  modules/admin_manual/images/enterprise/external_storage/windows_network_drive/wnd-ldap-exposed-user-attributes.png
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#1317 [10.14] [PR 1197] Update docker install guide to use Compose v2
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#1320 Update Transifex URL
  modules/developer_manual/pages/app/advanced/l10n.adoc
Labels: developer docs

#1321 [10.14] [PR 1320] Update Transifex URL
  modules/developer_manual/pages/app/advanced/l10n.adoc
Labels: backport

#1322 [10.13] [PR 1320] Update Transifex URL
  modules/developer_manual/pages/app/advanced/l10n.adoc
Labels: backport

#1325 [10.15] [PR 1323] Update migrating_to_kiteworks.adoc fix verify cmd
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: backport

#1324 [10.14] [PR 1323] Update migrating_to_kiteworks.adoc fix verify cmd
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: backport

#1328 [10.14] [PR 1326] fix: rclone is bundled + guest users will be migrated
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: backport

#1329 [10.15] [PR 1326] fix: rclone is bundled + guest users will be migrated
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: backport

#1333 [10.15] doc: review migrating to kiteworks
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: backport

#1334 [10.14] doc: review migrating to kiteworks
  modules/admin_manual/pages/maintenance/migrating_to_kiteworks.adoc
Labels: backport
