Repository owncloud/docs-server, pull requests merged in 2024-01, with the labels that each got.

#1226 Fix download link address for upgrades to be the same as in wget command below
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: documentation

#1227 [10.12] [PR 1226] Fix download link address for upgrades to be the sa…
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#1228 [10.13] [PR 1226] Fix download link address for upgrades to be the sa…
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#1230 Fix faulty xrefs found during the antora upgrade
  modules/admin_manual/pages/installation/apps_supported.adoc
Labels: admin docs

#1235 Fix links mostly to the server release notes
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: deployment

#1236 [10.12] [PR 1235] Fix links mostly to the server release notes
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#1237 [10.13] [PR 1235] Fix links mostly to the server release notes
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/user/custom_groups_app.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#1239 [10.12] [PR 1238] One more xref to absolute path change
  modules/admin_manual/partials/maintenance/major_release_note.adoc
Labels: backport

#1240 [10.13] [PR 1238] One more xref to absolute path change
  modules/admin_manual/partials/maintenance/major_release_note.adoc
Labels: backport

#1242 [10.13] [PR 1231] remove template editor from supported apps list
  modules/admin_manual/pages/installation/apps_supported.adoc
Labels: backport

#1241 [10.13] [PR 1232] remove references to templateeditor in email_config…
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: backport

#1219 Config to docs run based on changes in core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#1249 [10.13] [PR 1219] Config to docs run based on changes in core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#1250 [10.12] [PR 1219] Config to docs run based on changes in core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#1243 Antora 3.1 upgrade
  .drone.star
  antora.yml
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
  bin/optimize_crawl
  docs/new-version-branch.md
  es-docker-compose.yml
  ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
  modules/developer_manual/pages/core/apis/externalapi.adoc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
  modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/apis/ocs-user-sync-api.adoc
  modules/developer_manual/pages/core/apis/roles-api.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/developer_manual/pages/webdav_api/public_files.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
  package.json
  site.yml
  yarn.lock
Labels: dependencies, deployment

#1252 [10.12] [PR 1243] Antora 3.1 upgrade
  .drone.star
  antora.yml
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
  bin/optimize_crawl
  docs/new-version-branch.md
  es-docker-compose.yml
  ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
  modules/developer_manual/pages/core/apis/externalapi.adoc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
  modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/apis/ocs-user-sync-api.adoc
  modules/developer_manual/pages/core/apis/roles-api.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/developer_manual/pages/webdav_api/public_files.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
  package.json
  site.yml
  yarn.lock
Labels: backport

#1253 Update collabora_secure_view.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#1254 [master] [PR 1253] Update collabora_secure_view.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#1255 Just a small internal link fix
  docs/new-version-branch.md
Labels: documentation

#1257 [10.12] [PR 1255] Just a small internal link fix
  docs/new-version-branch.md
Labels: backport
