Repository owncloud/docs-server, pull requests merged in 2024-02, with the labels that each got.

#1258 Fix search index generation
  ext-antora/generate-index.js
Labels: deployment

#1259 [10.13] [PR 1258] Fix search index generation
  ext-antora/generate-index.js
Labels: backport

#1261 Update classification_and_policy_enforcement.adoc
  modules/admin_manual/images/enterprise/classification/document_classification.png
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: admin docs

#1262 [10.13] [PR 1261] Update classification_and_policy_enforcement.adoc
  modules/admin_manual/images/enterprise/classification/document_classification.png
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: backport

#1263 [10.12] [PR 1261] Update classification_and_policy_enforcement.adoc
  modules/admin_manual/images/enterprise/classification/document_classification.png
  modules/admin_manual/pages/enterprise/document_classification/classification_and_policy_enforcement.adoc
Labels: backport

#1264 ES index update
  ext-antora/generate-index.js
Labels: deployment

#1265 [10.13] [PR 1264] ES index update
  ext-antora/generate-index.js
Labels: backport

#1266 [10.12] [PR 1264] ES index update
  ext-antora/generate-index.js
Labels: backport

#1273 Config to Docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#1275 [10.12] [PR 1269] Update previews_configuration.adoc - PreviewProvider clarification
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
Labels: backport

#1276 Changes necessary for the 10.14 branch
  .drone.star
Labels: deployment
